[package]
name = "config-man"
version = "0.1.0"
authors = ["cam"]
edition = "2018"

[dependencies]
paw = "1.0"
serde = { version = "1.0", features = ["derive"] }
structopt = { version = "0.3", features = ["paw"] }
toml = "0.5"
