###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.

[skin]
default = "White none / White none"
tree = "Grey None / Grey None"
file = "Black None / Black None"
directory = "DarkBlue None Bold / DarkBlue None bold"
exe = "Green None"
link = "Cyan None"
pruning = "gray(16) None Italic"
perm__ = "Black None Bold"
perm_r = "Yellow None Bold"
perm_w = "DarkRed None Bold"
perm_x = "DarkGreen None Bold"
owner = "DarkYellow None Bold"
group = "DarkYellow None Bold"
count = "Yellow None"
dates = "DarkCyan None"
sparse = "ansi(214) None"
content_extract = "ansi(29) None"
content_match = "ansi(34) None"
git_branch = "Yellow None"
git_insertions = "Green None"
git_deletions = "DarkRed None"
git_status_current = "Black None"
git_status_modified = "Yellow None"
git_status_new = "Green None Bold"
git_status_ignored = "Black None"
git_status_conflicted = "Red None"
git_status_other = "Black None"
selected_line = "None gray(22)"
char_match = "Magenta None"
file_error = "Red None"
flag_label = "Black None"
flag_value = "DarkBlue None"
input = "Grey None"
status_error = "Black DarkRed"
status_job = "ansi(220) gray(20)"
status_normal = "Black gray(20)"
status_italic = "Black gray(20) Italic"
status_bold = "Black gray(20) Bold"
status_code = "Black gray(20)"
status_ellipsis = "Grey grey(20)"
purpose_normal = "Black gray(20)"
purpose_italic = "Black gray(20) Italic"
purpose_bold = "Black gray(20) Bold"
purpose_ellipsis = "Black gray(20)"
scrollbar_track = "Grey None"
scrollbar_thumb = "Black None"
help_paragraph = "Grey None"
help_bold = "Grey None Bold"
help_italic = "Grey None Italic"
help_code = "Grey gray(20)"
help_headers = "DarkMagenta None"
help_table_border = "Black None"
preview = "Black gray(22)"
preview_line_number = "Black gray(20)"
preview_match = "Magenta None"
hex_null = "Black None"
hex_ascii_graphic = "Grey None"
hex_ascii_whitespace = "Black None"
hex_ascii_other = "Grey None"
hex_non_ascii = "Black None"

# You may find explanations and other skins on
#  https://dystroy.org/broot/skins
# for example a skin suitable for white backgrounds
