###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.

[skin]
default = "Black none / Black none"
tree = "White None / White None"
file = "Grey None / White None"
directory = "DarkBlue None Bold / DarkBlue None bold"
exe = "Green None"
link = "Cyan None"
pruning = "gray(12) None Italic"
perm__ = "White None Bold"
perm_r = "Yellow None Bold"
perm_w = "DarkRed None Bold"
perm_x = "DarkGreen None Bold"
owner = "DarkYellow None Bold"
group = "DarkYellow None Bold"
count = "Yellow None"
dates = "DarkCyan None"
sparse = "ansi(214) None"
content_extract = "ansi(29) None"
content_match = "ansi(34) None"
git_branch = "Yellow None"
git_insertions = "Green None"
git_deletions = "DarkRed None"
git_status_current = "White None"
git_status_modified = "Yellow None"
git_status_new = "Green None Bold"
git_status_ignored = "White None"
git_status_conflicted = "Red None"
git_status_other = "White None"
selected_line = "None gray(5) / None gray(4)"
char_match = "Magenta None"
file_error = "Red None"
flag_label = "White None"
flag_value = "Grey None"
input = "White None / gray(15) gray(2)"
status_error = "Black DarkRed"
status_job = "ansi(220) gray(5)"
status_normal = "Grey gray(3)"
status_italic = "Grey gray(3) Italic"
status_bold = "Grey gray(3) Bold"
status_code = "White gray(3)"
status_ellipsis = "Grey grey(3)"
purpose_normal = "White gray(2)"
purpose_italic = "White gray(2) Italic"
purpose_bold = "White gray(2) Bold"
purpose_ellipsis = "White gray(2)"
scrollbar_track = "Grey None / gray(4) None"
scrollbar_thumb = "White None / gray(14) None"
help_paragraph = "Grey None"
help_bold = "Grey None Bold"
help_italic = "Grey None Italic"
help_code = "Grey gray(3)"
help_headers = "DarkMagenta None"
help_table_border = "White None"
preview = "White gray(2)"
preview_line_number = "White gray(2)"
preview_match = "Magenta None"
hex_null = "White None"
hex_ascii_graphic = "Grey None"
hex_ascii_whitespace = "White None"
hex_ascii_other = "Grey None"
hex_non_ascii = "White None"

# You may find explanations and other skins on
#  https://dystroy.org/broot/skins
# for example a skin suitable for white backgrounds
