use_nerdfont = true

[keybindings]
"q" = "share current"

[theme]
background = "black"
primary = "white"
secondary = "white"
title = "green"
playing = "green"
playing_selected = "green"
playing_bg = "black"
highlight = "white"
highlight_bg = "light black"
error = "red"
error_bg = "black"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "white"
cmdline_bg = "black"
